server:
  port: 8085

spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://mysql-payment:3306/payment_db
    username: aurastore
    password: aurastore123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    show-details: always

# Logs
logging:
  file:
    name: /app/logs/${spring.application.name}/${spring.application.name}.log

  logback:
    rollingpolicy:
      max-file-size: 10mb
      max-history: 10
