services:
  mysql:
    image: mysql:8.0
    container_name: mysql_discounts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discounts_db
      # MYSQL_USER: mysql8
      # MYSQL_PASSWORD: mysql8
    ports:
      - "3318:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
